# Generated by Django 4.1.3 on 2022-11-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('longitude', models.FloatField(max_length=10)),
                ('latitude', models.FloatField(max_length=10)),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal Code')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone Number')),
                ('images', models.ImageField(blank=True, max_length=10, null=True, upload_to='')),
                ('type', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('direction_link', models.URLField(null=True)),
            ],
        ),
    ]
