# Generated by Django 4.1.3 on 2022-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_remove_studio_images_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='images',
            field=models.ImageField(blank=True, max_length=10, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
