# Generated by Django 4.1.3 on 2022-12-09 02:26

from django.db import migrations, models
import studios.models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0007_alter_studio_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='images',
            field=models.ImageField(blank=True, default='posts/default.jpg', null=True, upload_to=studios.models.upload_to),
        ),
    ]
