# Generated by Django 4.1.3 on 2022-11-17 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('coach', models.CharField(max_length=150, null=True)),
                ('keywords', models.TextField(max_length=500, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('end_recur_date_time', models.DateTimeField()),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='ClassesInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('coach', models.CharField(max_length=150, null=True)),
                ('keywords', models.TextField(max_length=500, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('curr_enrollment', models.PositiveIntegerField(default=0, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('h_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='classes.classes')),
            ],
        ),
    ]
