# Generated by Django 4.1.2 on 2022-11-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classes_coach_alter_classes_description_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classes',
            field=models.ManyToManyField(blank=True, to='classes.classesinstance'),
        ),
    ]
