# Generated by Django 4.1.3 on 2022-11-17 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.DecimalField(decimal_places=2, max_digits=9)),
                ('type', models.CharField(default='day', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscribe_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('make_choices', models.CharField(choices=[('1', 'payment is made immediately after subscription.'), ('2', 'each upcoming payment will be automatically made in the beginning of their period.')], max_length=1)),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('card_info', models.CharField(default='xxxxxxxxxxxxxxxx', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('subscription_amount', models.IntegerField(default=0)),
                ('make_choices', models.CharField(choices=[('1', 'payment is made immediately after subscription.'), ('2', 'each upcoming payment will be automatically made in the beginning of their period.')], default='1', max_length=1)),
                ('transaction_time', models.DateTimeField()),
                ('card_info', models.CharField(default='xxxxxxxxxxxxxxxx', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription')),
            ],
        ),
    ]
