# Generated by Django 4.1.3 on 2022-11-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='make_choices',
            field=models.CharField(choices=[('2', 'each upcoming payment will be automatically made in the beginning of their period.'), ('1', 'payment is made immediately after subscription.')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='make_choices',
            field=models.CharField(choices=[('2', 'each upcoming payment will be automatically made in the beginning of their period.'), ('1', 'payment is made immediately after subscription.')], max_length=1),
        ),
    ]
