# Generated by Django 4.1.3 on 2022-12-03 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionpayment_make_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='make_choices',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='make_choices',
        ),
    ]
